name:  Build Prod Images
run-name: Build Prod Images

on:
  push:
    branches:
      - main

env:
  AWS_DEV_ACCOUNT_ID: ${{ secrets.AWS_DEV_ACCOUNT_ID }}
  AWS_DEV_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}
  AWS_DEV_ACCESS_KEY: ${{ secrets.AWS_DEV_ACCESS_KEY }}


jobs:
  checkout_code:
    name: Checkout Code
    uses: actions/checkout@v4